
PROTO_PATH=./proto

all:
	protoc --cpp_out=../cpp head.proto pay.proto client.proto product.proto crs.proto portal.proto saleprice.proto pproxy.proto order.proto cft.proto
	protoc --python_out=../py head.proto pay.proto client.proto product.proto crs.proto portal.proto saleprice.proto pproxy.proto order.proto cft.proto

